name: CI

on: 
  workflow_dispatch: 
  
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu]
  steps: 
  - uses: actions/checkout@v3
  
  - name: Print
    run: echo "Hello GitHub"
  
